### ISSUE TITLE
Prevent SQL Injection in some methods

### ISSUE THREAD

**Issue by hd132506** [dudu0166/OSS_SW_7_TodoList#10]
입력받은 데이터로 삽입/수정 쿼리를 사용하는 함수에서 SQL인젝션 방지하기
[Stackoverflow](https://stackoverflow.com/questions/1812891/java-escape-string-to-prevent-sql-injection)에서 방법이 나와 있는데, SQLite에서도 유효한지는 모르겠습니다.

**Comment by dudu0166** [comment]
제가 해결하겠습니다.
