### ISSUE TITLE
비정상적으로 종료되었을 때 Database locked 문제

### ISSUE THREAD

**Issue by hd132506** [dudu0166/OSS_SW_7_TodoList#16]
Ctrl + Z 등 프로그램을 비정상적으로 종료하고 재접속했을 때 DB 커넥션이 제대로 close 되지 않아 Database locked 오류가 뜨는 것 같습니다. 해결할 방법이 있을까요?

**Comment by dudu0166** [comment]
시나리오를 정확히 할 수 있을까요? 
제가 테스트 해 봤을 때는 Ctrl + Z로 종료 후 재접속해도 오류가 발생하지 않습니다... 
Windows 10과 Mac 환경에서 테스트했습니다.

**Comment by hd132506** [comment]
환경은 Mac이고 실행 중 강제종료하고 재실행할 때나 데이터를 추가하는 순간에 떴었는데 지금은 또 안 뜨네요... 몇 번 테스트해보고 이상 없으면 클로즈하겠습니다.
